<?php
$this->headLink()->appendStylesheet('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick.min.css');
$this->headLink()->appendStylesheet('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick-theme.min.css');
$this->headLink()->appendStylesheet($this->assetUrl('css/item-carousel.css', 'ItemCarouselBlock'));
$this->headScript()->appendFile('//cdn.jsdelivr.net/npm/@accessible360/accessible-slick@1.0.1/slick/slick.min.js');
$this->headScript()->appendFile($this->assetUrl('js/carousel-configurator.js', 'ItemCarouselBlock'));

$carouselID = 'carousel-' . $blockID;
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>
<div class="carousel-block">
	<?php if ($this->carouselHeading): ?>
	<h2><?php echo $this->carouselHeading; ?></h2>
	<?php endif; ?>
	<div class="<?php echo $carouselID; ?>">
	<?php
		foreach ($resources as $item) {
			// Skip if item doesn't exist
			if (!$item) {
				continue;
			}
			$media = $item->primaryMedia();
			$title = '';
						
			if ($this->showTitleOption == 'item_title') {
				$title = $item->displayTitle(null, $valueLang);
			} elseif ($this->showTitleOption == 'file_name') {			
				$title = $media ? $media->displayTitle(null, $valueLang) : $item->displayTitle(null, $valueLang);
			}
			
			if ($this->showTitleOption == 'no_title') {
				$textDiv = '';
			} else {			
				$textDiv = sprintf('<div class="slide-text"><div class="title">%s</div></div>', $title);
			}
			
			if ($media) {
				$slide = $this->thumbnail($media, $this->thumbnailType) . $textDiv;
				echo '<div>' . $item->linkRaw($slide) . '</div>';
			} else {
				$slide = $textDiv;
				echo '<div>' . $item->linkRaw($slide) . '</div>';
			} 
		}
	?>
	</div>

	<script>
    document.addEventListener('DOMContentLoaded', function() {
        const carouselOptions = {
            perPage: <?php echo $this->perPage ?>,
            loop: <?php echo $this->loop ?>,
            fade: <?php echo $this->fade ?>,
			floatCaption: <?php echo $this->floatCaption ?>,
            autoSlideDuration: <?php echo $this->autoSlideDuration ?>,
            slideCSSTextAlign: '<?php echo $this->slideCSSTextAlign ?>',
            slideCSSStretch: '<?php echo $this->slideCSSStretch ?>',
            thumbnailType: '<?php echo $this->thumbnailType ?>'
        };

        initializeCarousel('<?php echo $carouselID ?>', carouselOptions);
    });
    </script>
</div>
